# Generated by Django 4.0.1 on 2022-06-30 06:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('songs_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None)),
            ],
        ),
    ]
