# Generated by Django 4.0.1 on 2022-01-22 20:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songsapi', '0005_remove_recommendedsong_song_delete_songembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongEmbedding',
            fields=[
                ('row_number', models.IntegerField(default=-1)),
                ('song_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommends_songs_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None), size=None)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songsapi.dfsong')),
            ],
        ),
    ]
