# Generated by Django 4.0.1 on 2022-06-30 06:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEdge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist1', models.CharField(default='', max_length=100)),
                ('artist2', models.CharField(default='', max_length=100)),
                ('weight', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DFArtist',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DFSong',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('artist', models.CharField(default='', max_length=1000)),
                ('artist2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('songUrl', models.URLField()),
                ('imageUrl', models.URLField()),
                ('lyric', models.TextField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('genre', models.CharField(default='', max_length=100)),
                ('tokens', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSongs',
            fields=[
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songsapi.dfsong')),
                ('recommends_songs_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
            ],
        ),
    ]
