# Generated by Django 4.0.1 on 2022-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFArtist',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SongLikes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='dfsong',
            name='likes',
        ),
        migrations.AddConstraint(
            model_name='songlikes',
            constraint=models.UniqueConstraint(fields=('song_id', 'user_id'), name='unique_user_id_song_id_combination'),
        ),
    ]
