# Generated by Django 4.0.1 on 2022-06-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfartist',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
