# Generated by Django 4.0.1 on 2022-06-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongComments',
        ),
        migrations.DeleteModel(
            name='SongComments1',
        ),
        migrations.DeleteModel(
            name='SongComments2',
        ),
        migrations.DeleteModel(
            name='SongLikes',
        ),
    ]
