# Generated by Django 4.0.1 on 2022-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfsong',
            name='tokens',
            field=models.TextField(default=''),
        ),
    ]
