# Generated by Django 4.0.1 on 2022-06-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComments1',
            fields=[
                ('song_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
