# Generated by Django 4.0.1 on 2022-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfsong',
            name='lyric',
            field=models.TextField(null=True),
        ),
    ]
