# Generated by Django 4.0.1 on 2022-06-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0002_dfartist_songlikes_remove_dfsong_likes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songlikes',
            name='unique_user_id_song_id_combination',
        ),
        migrations.AlterUniqueTogether(
            name='songlikes',
            unique_together={('song_id', 'user_id')},
        ),
    ]
