# Generated by Django 4.0.1 on 2022-06-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0002_dfsong_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedsongs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songsapi.dfsong'),
        ),
    ]
