# Generated by Django 4.0.1 on 2022-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0002_alter_dfsong_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfsong',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
