# Generated by Django 4.0.1 on 2022-07-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0002_rename_imageurl_dfartist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfsong',
            name='artist2',
        ),
        migrations.AlterField(
            model_name='artistedge',
            name='artist1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist1', to='songsapi.dfartist'),
        ),
        migrations.AlterField(
            model_name='artistedge',
            name='artist2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist2', to='songsapi.dfartist'),
        ),
    ]
