# Generated by Django 4.0.1 on 2022-06-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0003_remove_songlikes_unique_user_id_song_id_combination_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songlikes',
            unique_together=set(),
        ),
    ]
