# Generated by Django 4.0.1 on 2022-06-29 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0003_alter_recommendedsongs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfsong',
            name='artist2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None),
        ),
    ]
