# Generated by Django 4.0.1 on 2022-07-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0003_remove_dfsong_artist2_alter_artistedge_artist1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedsongs',
            name='song',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songsapi.dfsong'),
        ),
    ]
