# Generated by Django 4.0.1 on 2022-01-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0004_songembedding_row_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedsong',
            name='song',
        ),
        migrations.DeleteModel(
            name='SongEmbedding',
        ),
        migrations.DeleteModel(
            name='RecommendedSong',
        ),
    ]
