# Generated by Django 4.0.1 on 2022-07-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0004_alter_recommendedsongs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedsongs',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songsapi.dfsong'),
        ),
    ]
