# Generated by Django 4.0.1 on 2022-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0004_alter_songlikes_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
