# Generated by Django 4.0.1 on 2022-06-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0004_alter_dfsong_artist2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistEdge',
        ),
    ]
