# Generated by Django 4.0.1 on 2022-05-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0005_remove_recommendedsong_song_delete_songembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=1000)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
