# Generated by Django 4.0.1 on 2022-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0005_delete_artistedge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist1', models.CharField(default='', max_length=100)),
                ('artist2', models.CharField(default='', max_length=100)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
