# Generated by Django 4.0.1 on 2022-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0006_artistedge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistedge',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artistedge',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
