# Generated by Django 4.0.1 on 2022-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songsapi', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListenSong',
            fields=[
                ('usid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=250)),
                ('artist', models.CharField(default='', max_length=250)),
                ('user_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
