translate_popular_songs = "آهنگ های معروف"
translate_traditional_popular_songs = "آهنگ های سنتی و محلی"
translate_rec_songs = "آهنگ های پیشنهادی مخصوص شما"
translate_rec_artists = "خواننده های مورد علاقه شما"
translate_history_playlist = "قبلا گوش دادید:)"
